### ISSUE TITLE
Make error box dismissable

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/chat-ui#26]
![image](https://user-images.githubusercontent.com/188915/77844903-a8e23f00-71aa-11ea-829e-6c453bad08a5.png)

After trying to create a new chat, the red error message bar doesn't disappear from the bottom when you try and do a new action.

## User Story

As a user
I can dismiss the error box
when I have read the error message

**Comment by vipin8169** [comment]
How to reproduce this error? can i use a wrong token, does that work?

**Comment by coderbyheart** [comment]
Yes, that will show an error.

**Comment by vipin8169** [comment]
Sounds good, I will take a look now

**Comment by coderbyheart** [comment]
Closed via #44
