### ISSUE TITLE
Need way for user to subscribe to channel

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/chat-ui#9]
**User Story**

As a user
I can subscribe to a channel
so I receive email notifications if I am offline

**Needs**

A way for the user to provide their email and one or more channels they want to *subscribe*.

**Comment by coderbyheart** [comment]
The GraphQL mutation `enableChannelNotifications` is described [here](https://github.com/distributeaid/twilio-integration/blob/5e1b60b78063fd41310f43ffb570012f78bb4f4b/features/EnabledEmailNotifications.feature#L17)

**Comment by Tangerinez** [comment]
Will be tackling this a bit today
